server:
  port: 8081
  host: 0.0.0.0

app:
    name: "catalog-service"

db:
  init-schema: true
  init-data: true
  source: jdbc
  connection:
    url: jdbc:mysql://127.0.0.1:6603/catalog-service-db?useSSL=false
    username: root
    password: root
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: "SELECT 0"
    create-table-product-categories: "CREATE TABLE product_categories (
      id int(11) NOT NULL AUTO_INCREMENT,
      name varchar(45) NOT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4"
    insert-product-category: "INSERT INTO product_categories(id, name) VALUES (?, ?)"
    create-table-products: "CREATE TABLE products (
      id int(11) NOT NULL AUTO_INCREMENT,
      name varchar(45) NOT NULL,
      category_id int(11) NOT NULL,
      PRIMARY KEY (id),
      KEY fk_products_category_fk_idx (category_id),
      CONSTRAINT fk_products_category_fk FOREIGN KEY (category_id) REFERENCES product_categories (id)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4"

